<?php

namespace SwAlgolia;

use Doctrine\Common\Collections\ArrayCollection;
use Shopware\Components\Plugin;
use Shopware\Components\Plugin\Context\ActivateContext;
use Shopware\Components\Plugin\Context\DeactivateContext;
use Shopware\Components\Plugin\Context\InstallContext;
use Shopware\Components\Plugin\Context\UpdateContext;
use Shopware\Components\Plugin\Context\UninstallContext;
use Shopware\Components\Theme\LessDefinition;
use Symfony\Component\DependencyInjection\ContainerBuilder;

// Composer autoload
require_once(__DIR__.'/vendor/autoload.php');

/**
 * Class SwAlgolia
 * Plugin main class for Algolia search
 * @package SwAlgolia
 */
class SwAlgolia extends Plugin
{

    public function install(InstallContext $context)
    {

//        // @TODO Remove this demo attributes
//        // Create some additional attributes
//        $attributeService = Shopware()->Container()->get('shopware_attribute.crud_service');
//        $attributeService->update('s_articles_attributes', 'swalgolia_attr1', 'string', [
//                'label' => 'SwAlgolia Attr 1',
//                'supportText' => 'Demo attribute',
//                'translatable' => true,
//                'displayInBackend' => true,
//                'position' => 50
//            ]
//        );
//
//        // Rebuild attribute models
//        $metaDataCache = Shopware()->Models()->getConfiguration()->getMetadataCacheImpl();
//        $metaDataCache->deleteAll();
//
//        Shopware()->Models()->generateAttributeModels(
//            array('s_articles_attributes')
//        );

        parent::install($context);
    }

    public function uninstall(UninstallContext $context)
    {

//        $attributeService = Shopware()->Container()->get('shopware_attribute.crud_service');
//        $attributeService->delete('s_articles_attributes', 'swalgolia_attr1');
//
//        // Rebuild attribute models
//        $metaDataCache = Shopware()->Models()->getConfiguration()->getMetadataCacheImpl();
//        $metaDataCache->deleteAll();
//
//        Shopware()->Models()->generateAttributeModels(
//            array('s_articles_attributes')
//        );

        parent::uninstall($context); // TODO: Change the autogenerated stub
    }

    public function build(ContainerBuilder $container)
    {
        parent::build($container);
        $container->setParameter('sw_algolia.plugin_dir', $this->getPath());
    }
}
